"""empty message

Revision ID: 7442c0a30337
Revises: 827e2ae8fd9a
Create Date: 2022-05-25 15:39:09.353821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7442c0a30337'
down_revision = '827e2ae8fd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user-id', sa.Integer(), nullable = False),
    sa.Column('post_id', sa.Integer(), nullable = False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete ='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete ='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
