# Generated by Django 3.2.11 on 2022-06-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='abbreviations', max_length=255),
        ),
    ]
