# Generated by Django 4.0.5 on 2022-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='abbreviations', max_length=250),
        ),
    ]
