# Generated by Django 3.2.11 on 2022-06-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220627_1211'),
        ('blog', '0014_post_author'),
    ]

    operations = [
    ]
